name: e2e test

on:
  pull_request:

jobs:
  e2e_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod

      - name: Prepare e2e test
        run: |
          go build -o ./tap-etherip-config-sync ./cmd/tap-etherip-config-sync
          go build -o ./e2etest ./cmd/e2etest

      - name: Run e2e test
        run: |
          sudo ./e2etest
